### ISSUE TITLE
Improve the ui/ux of the application

### ISSUE THREAD

**Issue by piyushverma001** [piyushverma001/COVID-19-Tracker-App#4]
The present ui/ux can be modified to add features such as light/dark mode and few improvements in font styles.

**Comment by itsnitinr** [comment]
Hi, I could add a dark theme to the website. Shall I ?

**Comment by Sayan-dev** [comment]
Working on it?

**Comment by piyushverma001** [comment]
Yes @itsnitinr @Sayan-dev  both of you can go ahead!
Happy Hacking!

**Comment by itsnitinr** [comment]
Yes @Sayan-dev . Started with the dark mode. Maybe you can try to fix some other UI/UX related stuff.

**Comment by yogmel** [comment]
Hi @piyushverma001 
Can I experiment with font styles and colors maybe?

**Comment by piyushverma001** [comment]
@yogmel Yeah please go ahead!

**Comment by jennypoon** [comment]
Do you mind if I experiment with the UI a bit? Thinking of making the graphs a bit smaller to avoid the scroll bars and adjusting the dropdown so it doesn't take up the full height of the window.

**Comment by piyushverma001** [comment]
@jennypoon sure please make changes you feel would improve the application. Ill review it!
