### ISSUE TITLE
Page disappear when clicking on countries and after animation stops

### ISSUE THREAD

**Issue by viriyadhika** [piyushverma001/COVID-19-Tracker-App#6]
Error 502 when getting https://covid19.mathdro.id/api/daily

**Comment by Sayan-dev** [comment]
I understood the error, working on it

**Comment by viriyadhika** [comment]
API is currently down now. I found out you can fix it by doing this (change in bold, so at least the app doesn't break even though the API is breaking) :)

const Chart = ({data : { confirmed, deaths, recovered}, country}) => {
    const [dailyData, setDailyData] = **useState();**

    useEffect(() => {
        const fetchAPI = async () => {
            setDailyData(await fetchDailyData());
        }

        //console.log(dailyData);
        fetchAPI();
    } , []);
    

    const lineChart = (
        **dailyData**
        ?(
        <Line
        data={{
            labels: dailyData.map(({ date }) => date),
            datasets: [{
                data: dailyData.map(({ confirmed }) => confirmed),
                label: 'Infected',
                borderColor: '#3333ff',
                fill: true,
            }, 
            {
                data: dailyData.map(({ deaths }) => deaths),
                label: 'Deaths',
                borderColor:'red',
               // borderColor: 'rgba(255,0,0,0.5)',
                fill: true,
            }],
        }}
        />) :null
    );

**Comment by piyushverma001** [comment]
Yeah looks like the api is down! No issues go ahead make the required changes and make a PR ;)
Happy hacking!
